### ISSUE TITLE
consider adding an OSI license

### ISSUE THREAD

**Issue by only1chunts** [kelewinska/FONDA_trends-nf#1]
Hi,
Would you consider adding an [OSI license](https://opensource.org/license) to this repo so that user are in no doubt as to what they can use its content for.
Many thanks.

**Comment by kelewinska** [comment]
Hi, 
Thanks for pointing this out. Since FONDA project is a basic-research project, the repository is now shared under the [GPL-3.0 license](https://github.com/kelewinska/FONDA_trends-nf#GPL-3.0-1-ov-file).
